<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        //Hereâ€™s an example when all promises fail:
        Promise.any([
            new Promise((resolve, reject) => setTimeout(() => reject(new Error("Ouch!")), 1000)),
            new Promise((resolve, reject) => setTimeout(() => reject(new Error("Error!")), 2000))
        ]).catch(error => {
            console.log(error.constructor.name); // AggregateError
            console.log(error.errors[0]); // Error: Ouch!
            console.log(error.errors[1]); // Error: Error!
        });

        //As you can see, error objects for failed promises are available in the errors property of the AggregateError object.

    </script>
</body>
</html>